export const ACTIONS_SECRET_SANTA = {
    TOGGLE_EDIT: 'TOGGLE_EDIT_SECRET_SANTA',
    DELETE: 'DELETE_SECRET_SANTA',
    UPDATE: 'UPDATE_SECRET_SANTA',
    CREATE: 'CREATE_SECRET_SANTA',
    SEND: 'SEND_SECRET_SANTAS',
    SEND_SUCCESS: 'SEND_SECRET_SANTA_SUCCESS',
    SEND_ERROR: 'SEND_SECRET_SANTA_SUCCESS'
};